name: DocFX

on:
  push:
    branches: [ master ]
  
jobs:
  DocFX:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: nikeee/docfx-action@master
      name: Build Documentation
      with:
        args: PersistentStorage/docfx.json

    # Publish generated site using GitHub Pages
    - uses: maxheld83/ghpages@master
      name: Publish Documentation on GitHub Pages
      env:
        BUILD_DIR: _site 
        GH_PAT: ${{ secrets.GH_PAT }}
