name: Deploy Documentation

on:
  push:
    branches: [ master ]
  
jobs:
  docfx:
  
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
      
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    
    - name: Restore Dependencies
      run: msbuild -t:restore
      
    - name: Build Project
      run: msbuild PersistentStorage.sln
    
    - name: Publish Documentation to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v1
      with:
        target_branch: gh-pages
        build_dir: docs/_site
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
