name: DocFX

on:
  push:
    branches: [ master ]
  
jobs:
  DocFX:
  
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - run: choco install docfx
    - run: docfx init -q
    - run: docfx PersistentStorage\docfx.json --serve
    # Publish generated site using GitHub Pages
    - uses: maxheld83/ghpages@master
      name: Publish Documentation on GitHub Pages
      env:
        BUILD_DIR: _site 
        GH_PAT: ${{ secrets.GH_PAT }}
